name: Sync ElevenLabs Calls

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Вот это место нужно исправить
      - name: Run sync script
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_AGENT_ID: ${{ secrets.ELEVENLABS_AGENT_ID }} # <-- ВОТ ЭТА СТРОКА ОТСУТСТВОВАЛА
          GOOGLE_DOC_ID: ${{ secrets.GOOGLE_DOC_ID }}
          GOOGLE_DRIVE_FOLDER_ID: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: python main.py

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add processed_ids.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update processed IDs" && git push)
